---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  client_rb:
    audit_mode: :disabled

platforms:
  - name: debian7
    driver:
      box: 'chef/debian7'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

  - name: debian8
    driver:
      box: 'chef/debian8'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.2_chef-provisionerless.box

  - name: ubuntu12
    driver:
      box: 'chef/ubuntu-12.04'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

  - name: ubuntu14
    driver:
      box: 'chef/ubuntu-14.04'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

  - name: ubuntu15
    driver:
      box: 'chef/ubuntu-15.04'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box

  - name: centos6
    driver:
      box: 'chef/centos-6.7'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box

  - name: centos7
    driver:
      box: 'chef/centos-7.1'
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box


suites:
  - name: host
    run_list:
      - recipe[kvm::host]
  - name: guest
    run_list:
      - recipe[kvm::guest]

